### ISSUE TITLE
Prevent users from editing `filename` property on classes

### ISSUE THREAD

**Issue by jgd10** [pyansys/pymapdl-reader#104]
Whilst working on https://github.com/pyansys/pymapdl-reader/issues/98 I have made explicit `filename` and `pathlib_filename` properties on classes that have the `filename` property. I kept a setter for `filename` because to remove it would be a breaking change.

Additionally, whilst working on the tests for these changes I notice that if an invalid filename is provided the class constructor will throw an error, but obviously this wasn't happening with the setters then and it isn't happening with the setters I've added now. Do we want people to be able to set the filename like this? This would be on the Result class or Archive class, for example. 

It would be trivial to delete the new setter methods before making my PR. Or alternatively I could add a check to the setters? However, this would still be a breaking change since this wasn't in the original behaviour. I would suggest just deleting the setters as it seems like you get undefined behaviour otherwise and the filename would still be accessible by the `_filename` property anyway if a user was particularly determined.

What do you think @akaszynski ?

Classes this affects:

 - `EmatFile`
 - `FullFile`
 - `Archive`
 - `Result`

**Comment by akaszynski** [comment]
> It would be trivial to delete the new setter methods before making my PR. Or alternatively I could add a check to the setters? However, this would still be a breaking change since this wasn't in the original behaviour. I would suggest just deleting the setters as it seems like you get undefined behaviour otherwise and the filename would still be accessible by the _filename property anyway if a user was particularly determined.

I think deleting the setters is the most straightforward approach.
