### ISSUE TITLE
Import material stress limits

### ISSUE THREAD

**Issue by NDfp** [pyansys/pymapdl-reader#109]
Hello,
I would like to import from a .rst file the stress limits associated with a material.
This information should be included in the .rst file.
In pyansys I have found the mesh.materials property but it does not include the stress limits.
Is there a function implemented for reading these data?

**Comment by NDfp** [comment]
Update:
I checked in Ansys Classic. There I can see the data with TBLIST. It seems the data is stored in a table. I could however not find where (and if) these are imported. There is a ptrDSIl imported in rst.py but it seems to import the result tables only.

**Comment by akaszynski** [comment]
Hi @NDfp, can you upload a basic rst containing the stress limits? I'll add it to the unit testing and get the feature added.

**Comment by NDfp** [comment]
Hi Alex,
that sounds great!
I'll try to attach a test model. If it doesn't work, I will send you via
email.
Thank you
Francesco

**Comment by NDfp** [comment]
It works like a charm. Thank you a lot!
