### ISSUE TITLE
result.animate_nodal_displacement() crashes

### ISSUE THREAD

**Issue by pmaroneh** [pyansys/pymapdl-reader#112]
I've run a modal analysis, which I'd like to postprocess. 
```
result = mapdl.result
result.animate_nodal_displacement(1)
```
does create an animation of the first mode
![image](https://user-images.githubusercontent.com/76440649/154487535-0feb0e6b-0f44-4dd0-8006-fbb4378831bb.png)
but when closing the plot window, the following error is returned:
![image](https://user-images.githubusercontent.com/76440649/154487770-61647a17-96da-4099-8c95-523901170e48.png)

I'll paste the complete error message in comment, but I don't know how to address this.

**Comment by germa89** [comment]
Transferred to pymapdl reader because the error is in that library.
