### ISSUE TITLE
Material ID incorrect

### ISSUE THREAD

**Issue by NDfp** [pyansys/pymapdl-reader#119]
Hello,
When importing the materials:
`result.materials`
the materials are numbered consecutively starting from 1.
In the element-material association vector:
`result.mesh.material_type`
the IDs differ from the ones in the material list.
When considering the unique number of IDs in `material_type`, the number of materials in `materials` is obtained.
I assume the ID in the `materials` list is incorrect.
Could you please check it?
Thank you
Regards
Francesco

**Comment by NDfp** [comment]
Some more details:
The key is defined in:
`self._materials[mat_data_ptr[0]] = material`
`mat_data_ptr` is defined in:
`idx_st = 3 + i*(n_mat_prop + 1)`
`idx_en = 3 + i*(n_mat_prop + 1) + 1 + n_mat_prop`
`mat_data_ptr = mat_table[idx_st:idx_en]`
From the documentation, "last 2 data contains the active table number and material ID". I however did not find in the record anything similar to the ID (apart from the first value).

**Comment by akaszynski** [comment]
I'll look into this. Thanks for posing the issue!

**Comment by NDfp** [comment]
Another point. With a model (which unfortunately I cannot share) I had more unique entries in `material_type` than in `materials`.
Btw, Ansys appears to duplicate the the material definitions: I have significantly more materials in the rst as in Engineering Data.

**Comment by pmaroneh** [comment]
Hello @NDfp. To reply to your comment: Mechanical will create one material ID per body, so if only one material is defined in Engineering Data but the model has three different bodies, the .rst file will show three mat IDs (but the material properties will be the same of course).

**Comment by NDfp** [comment]
Hi Alex,
do you have an update concerning this issue?
Regards
Francesco

**Comment by akaszynski** [comment]
Hi @NDfp,

I've looked into this and it appears that the result is reading in the material type correctly:

In:
```
mat_data_ptr = mat_table[idx_st:idx_en]
```

We store the material data by material number in:
```
# store by material number
self._materials[mat_data_ptr[0]] = material
```

Which is the first item in the material data pointer array.

Please email me at alexander.kaszynski@ansys.com and let's see if there's a way we can share the rst file.

**Comment by NDfp** [comment]
Hi Alex,
in the file I have sent you, the ID of the materials in self._materials ranges from 1 to 7.
In self.mesh.material_type the IDs range between 1 to 14. Is there another variable containing the material ID for all the elements?
Regards
Francesco

**Comment by NDfp** [comment]
Maybe a question first. Is self.mesh.material_type the correct entity? If not, where do I find the material ID for each element?

**Comment by NDfp** [comment]
@akaszynski FYI my office mail is not working. In case you need to contact me, please use github or my private email

**Comment by NDfp** [comment]
Hi,
Do you have any update on this issue?

**Comment by rlagha** [comment]
@NDfp Do you have Ansys 2022R2 install? if so you can try to get this data using pydpf.

**Comment by NDfp** [comment]
Unfortunately not. At the moment 2021R2.
If possible I would however prefer to stay in the pyansys environment; changing the whole code would be quite some work...

**Comment by NDfp** [comment]
Unfortunately at the moment I do not have 2022 (and I cannot install it since we have not yet fully recovered from a cyber attack).
@rlagha could you maybe test it for me? I can provide the model if Alex has not done so yet.
@akaszynski is there a chance of having the issue patched in pyansys?

**Comment by rlagha** [comment]
@NDfp , is your question to have the associativity between the elements and the materials? if so, the yes with DPF you can get this.

**Comment by NDfp** [comment]
@rlagha sounds great. Dos it work also with 2021R2?
Have you tried also with the model I sent Alex? Just to be sure.
Otherwise, could you help me on how to do it? I have tried to use DPF but so far with very little success.

**Comment by dpfbuild** [comment]
@NDfp I did this with a server based on 2022R1 unfortunately. If you have access to it, this is great, otherwise soon we will provide DPF as a standalone server.

**Comment by NDfp** [comment]
At the moment we are unfortunately still not able to install new software. The newest installed version is 2021R2

**Comment by NDfp** [comment]
Hi Mike,
thank you for the suggestion and sorry for the delay.
I have passed the topic to my colleague Sven. He will get in touch with you.
Regards
Francesco

**Comment by mikerife** [comment]
Hi @germa89 I don't think the reader needs anything - it is reporting exactly what is in the model.  Mike

**Comment by nasdr** [comment]
Hey everyone,
also from my side: sorry for the delay. I'm currently familiarizing myself with the issue. I am trying to reproduce the error to be able to give more insights. In general I can say that we do not work with contacts but with merged nodes.
I will keep you posted.
Best regards
Sven

**Comment by germa89** [comment]
I'm closing this issue then. But if new related info appears, @nasdr and @NDfp feel free to reopen it or open a new one.

**Comment by mikerife** [comment]
Hi @nasdr Contact elements are not the only type that have material model capability but not always a reason to use a material model, and so could cause same behavior.  For example surface effect elements.  Some Joint elements.  In WM Mechanical the 'Deformable' and 'Rigid' connection types for "Remote" type of objects are attached to the model via contact elements.  As Joints can be.  So there may be contact elements in the model and you may not know.  Mike
