### ISSUE TITLE
Two documentation Examples do not scroll correctly.

### ISSUE THREAD

**Issue by mikerife** [pyansys/pymapdl-reader#157]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

https://reader.docs.pyansys.com/examples/00-read_binary/load_shaft_result.html#sphx-glr-examples-00-read-binary-load-shaft-result-py

https://reader.docs.pyansys.com/examples/01-cyclic_results/academic_sector_nd.html#sphx-glr-examples-01-cyclic-results-academic-sector-nd-py

When scrolling the web page of these two examples the example overlaps the example list on the upper left of the page.  But only for these two examples.  Here is what they look like:

![image](https://user-images.githubusercontent.com/91209185/195643520-37391332-17de-424d-ac27-25b0d98826ec.png)

Mike

### 📝 Steps to reproduce

Using Chrome Version 106.0.5249.103 (Official Build) 

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.9

### 📦 Installed packages

```shell
Not needed.
```

**Comment by akaszynski** [comment]
Should be resolved by #158. Thanks for pointing that out.
