### ISSUE TITLE
How to close file

### ISSUE THREAD

**Issue by xiaomaiAI** [pyansys/pymapdl-reader#16]
Hi,
    I found that after read `.rst` file by `read_binary`, the file did not close automatically. Is there any method or way to close it? Thank you.

**Comment by akaszynski** [comment]
I've found that you can get faster performance by keeping the file open rather than opening and closing it for each read.  If you need to close the file, you can `del <result object>` and the file will automatically close.  If it doesn't, we need to fix that.

**Comment by xiaomaiAI** [comment]
sorry，now the version I used is v0.44.5, a special version that does not store mesh datas, maybe this version could not `del` or something? may I modify the codes and make it works? Thank you.

**Comment by akaszynski** [comment]
You're always free to modify the code.  If you're familiar with GitHub, you could even create a fork of `pymapdl-reader` and then you can even start committing code and then pushing to your fork.  Otherwise, you can just copy the code on your machine and modify it locally.

**Comment by xiaomaiAI** [comment]
Thanks for your reply, I did not fork the `pyansys v0.44.5` which you modified to not store mesh data for me, and you remove this version soon. I only downloaded the release version by `pip`, so I have no idea about what did you modify on that version, or does the latest codes support switch off store mesh datas? Thank you.

**Comment by xiaomaiAI** [comment]
SORRY. my mistake, I find the version is `0.44.15`, not `0.44.5` , thanks for your help.
