### ISSUE TITLE
Import of mesh including radiation fails

### ISSUE THREAD

**Issue by JackGuyver** [pyansys/pymapdl-reader#17]
I recently created some thermal simulation cases that include radiation boundary conditions, exported the corresponding mesh to a CDB file and tried to read it using the `Archive` class:
```
from ansys.mapdl import reader as pymapdl_reader
arcv = pymapdl_reader.Archive("ErnoRadiation.CDB", parse_vtk=False)
```
For some cases the reader will then freeze. If I suppress the radiation bc, the mesh is read smoothly.
I was able to boil the effect down to a very simple testcase that I attached.

[Cube.zip](https://github.com/pyansys/pymapdl/files/6122006/Cube.zip)

**Comment by akaszynski** [comment]
Sorry this one took so long to get to.  I should be more careful when saying "over the weekend".

Bug is related to the placement of the RLBLOCK reader.  File reads correctly now, and be on the lookout the next release ``ansys-mapdl-reader``, which should be out by the end of today.

**Comment by JackGuyver** [comment]
No problem at all.
Getting the solution served on a (release-) plate after less then two weeks is still a wonderful response time and kind of support.
I can indeed confirm that my testcase now gets read exactly as expected. I'll move on to the more realistic geometries next.

Thank you very much for your fix, your work on this tool is very much appreciated!
