### ISSUE TITLE
pip installation ended with error

### ISSUE THREAD

**Issue by DKreuter** [pyansys/PyMAPDL-reader#20]
Hi, I have some problems installing pymapdl-reader using pip.
I use a plain environment (only python, pip and numpy, cython installed) and try to install pymapdl-reader.

But that ends up with the following error:

`
ERROR: Cannot install ansys-mapdl-reader because these package versions have conflicting dependencies.

The conflict is caused by:
    pyvista 0.29.0 depends on vtk
    pyvista 0.28.1 depends on vtk
    pyvista 0.28.0 depends on vtk
    pyvista 0.27.4 depends on vtk
    pyvista 0.27.3 depends on vtk
    pyvista 0.27.2 depends on vtk
`

I tried several ways of installing the pymapdl-reader (installing pyvista before and so on), but no chance to get it. 
It would be great to have a pip-ready version that handles this problems.

**Comment by akaszynski** [comment]
I'm guessing you're using Python 3.9 or some other python env that doesn't have a VTK wheel available.

VTK doesn't have a Python 3.9 solution (yet).  If you're working on a conda environment you can install the package as they have wheel for 3.9, but if outside of conda, use Python 3.8 for now until they have a wheel.

I'm working on implementing a Conda package for this module so these issues will be at least partially solved.

**Comment by DKreuter** [comment]
Great, thanks for the info. With python 3.8 everything works. Really great enhancements so far in the pymapdl-reader.

**Comment by akaszynski** [comment]
I'm keeping this open to remind myself to add a minimum version to the python_requires for now.  You can get around this with anaconda's VTK, so I may alternatively have to check if VTK is available for the platform/python version and then proceed with an install.

**Comment by akaszynski** [comment]
Resolved in #44
