### ISSUE TITLE
RLBLOCK read error

### ISSUE THREAD

**Issue by xiaomaiAI** [pyansys/pymapdl-reader#23]
Hi,
  Reading a `.cdb` file with `Archive()`, and there is something wrong in reading `RLBLOCK` lines, here is the file, Thanks.
[cdb_file.zip](https://github.com/pyansys/pymapdl-reader/files/6388599/cdb_file.zip)

**Comment by xiaomaiAI** [comment]
Sorry, the latest version is working.

**Comment by akaszynski** [comment]
Thanks for checking, was about to download.
