### ISSUE TITLE
Bug located in nodal_solution reading

### ISSUE THREAD

**Issue by Tony-ooo** [pyansys/pymapdl-reader#235]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

When using pymapdl-reader to read nodal solutions, the extracted values are mostly 0 with a few extreme maximum or minimum values, making it impossible to read normally.

### 📝 Steps to reproduce
Using Ansys 2023R1 workbench Static Analysis module.
The following code can be used to reproduce the issue：

> from ansys.mapdl import reader as pymapdl_reader
> rst = pymapdl_reader.read_binary(rstfile)
> DISP = rst.nodal_solution(0)
> Usis = DISP[1][:]

the values of "Usis" are mostly 0 with a few extreme maximum or minimum values, making it impossible to read normally.
!!!Note that: A project created solely using the Ansys 2023R1 Workbench static analysis module may encounter this issue, but projects saved using the Ansys 2021R2 Workbench static analysis module can be opened in Ansys 2023R1 Workbench and re-saved without encountering this issue. I suspect this to be a compatibility problem with Ansys 2023R1.

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

ANSYS 2023R1

### 🐍 Which Python version are you using?

3.8

### 📦 Installed packages

```shell
absl-py==1.4.0
ansys-dpf-core==0.8.0
ansys-dpf-gate==0.3.1
ansys-dpf-gatebin==0.3.1
ansys-dpf-post==0.4.0
ansys-grpc-dpf==0.7.1
ansys-mapdl-reader==0.52.11
appdirs==1.4.4
astunparse==1.6.3
Bottleneck==1.3.5
cachetools==5.3.0
certifi==2022.12.7
charset-normalizer==3.1.0
colorama==0.4.6
contourpy==1.0.7
cycler==0.11.0
et-xmlfile==1.1.0
flatbuffers==2.0.7
fonttools==4.39.3
gast==0.4.0
google-api-core==2.11.0
google-api-python-client==2.83.0
google-auth==2.17.2
google-auth-httplib2==0.1.0
google-auth-oauthlib==1.0.0
google-pasta==0.2.0
googleapis-common-protos==1.59.0
grpcio==1.53.0
h5py==3.8.0
httplib2==0.22.0
idna==3.4
imageio==2.27.0
importlib-metadata==6.1.0
importlib-resources==5.12.0
joblib==1.2.0
keras==2.7.0
Keras-Preprocessing==1.1.2
kiwisolver==1.4.4
libclang==16.0.0
Markdown==3.4.3
MarkupSafe==2.1.2
matplotlib==3.7.1
mkl-fft==1.3.1
mkl-random==1.2.2
mkl-service==2.4.0
numexpr==2.8.4
numpy==1.24.2
oauthlib==3.2.2
openpyxl==3.1.2
opt-einsum==3.3.0
packaging==23.0
pandas==1.5.3
Pillow==9.5.0
pip==23.0.1
platformdirs==3.2.0
pooch==1.7.0
protobuf==4.22.1
psutil==5.9.4
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyparsing==3.0.9
python-dateutil==2.8.2
pytz==2022.7
pyvista==0.38.5
requests==2.28.2
requests-oauthlib==1.3.1
rsa==4.9
scikit-learn==1.2.2
scipy==1.10.1
scooby==0.7.1
setuptools==67.6.1
six==1.16.0
tensorboard==2.12.1
tensorboard-data-server==0.7.0
tensorboard-plugin-wit==1.8.1
tensorflow-estimator==2.7.0
tensorflow-gpu==2.7.0
tensorflow-io-gcs-filesystem==0.31.0
termcolor==2.2.0
threadpoolctl==3.1.0
tqdm==4.65.0
typing_extensions==4.5.0
uritemplate==4.1.1
urllib3==1.26.15
vtk==9.2.6
Werkzeug==2.2.3
wheel==0.40.0
wincertstore==0.2
wrapt==1.15.0
zipp==3.15.0
```

**Comment by akaszynski** [comment]
This is another example where PyMAPDL Reader won't be able to keep up with MAPDL. There are compression changes occurring "under the hood" that are difficult to incorporate within this reader.

I'd strongly recommend transitioning to [PyDPF-Core](https://dpf.docs.pyansys.com/version/stable/). If you absolutely need support for this, email me at alexander.kaszynski@ansys.com and I can work something out with the powers that be.

**Comment by Tony-ooo** [comment]
> This is another example where PyMAPDL Reader won't be able to keep up with MAPDL. There are compression changes occurring "under the hood" that are difficult to incorporate within this reader.
> 
> I'd strongly recommend transitioning to [PyDPF-Core](https://dpf.docs.pyansys.com/version/stable/). If you absolutely need support for this, email me at [alexander.kaszynski@ansys.com](mailto:alexander.kaszynski@ansys.com) and I can work something out with the powers that be.

Because I want to extract the X-component, Y-component, Z-component of displacement and X-component, Y-component, Z-component of rotation for static mechanical simulation, I can only use pymapdl-reader. PyDPF-Core and PyDPF-Post cannot meet my requirements as they can only extract nodal solutions, including the X-component, Y-component, Z-component of displacement.

**Comment by akaszynski** [comment]
Please upload a minimum working example result file here as a zip archive and I'll do the best I can to support it. I will also email the developers of DPF and have these features added for the next release.

CC @PProfizi @rlagha

**Comment by Tony-ooo** [comment]
> Please upload a minimum working example result file here as a zip archive and I'll do the best I can to support it. I will also email the developers of DPF and have these features added for the next release.
> 
> CC @PProfizi @rlagha

Thank you so much for your help. Enclosed is a minimum working example result file that I have compressed into a zip archive. Kindly do your best to address this issue.
[nodal_solution.zip](https://github.com/pyansys/pymapdl-reader/files/11183480/nodal_solution.zip)

**Comment by PProfizi** [comment]
Hello @Tony-ooo ,

please find below an script showing how to extract rotational displacement values from the previously shared result files with PyDPF-Core.
Does this answer your need?
I will be adding this feature to the PyDPF-Post library as soon as possible.

```py
import ansys.dpf.core as dpf
import numpy as np

rstfile = r'D:/nodal_solution/file.rst'
datfile = r'D:/nodal_solution/ds.dat'

substep = 4

# create the DataSource
ds = dpf.DataSources()
ds.set_result_file_path(rstfile, key="rst")
ds.add_file_path(datfile, key="dat")

# instantiate a Model
model = dpf.Model(data_sources=ds)
print(model)

# define a time_scoping on substep 4
time_scoping = dpf.time_freq_scoping_factory.scoping_by_step_and_substep_from_model(
    load_step_id=1,
    subset_id=substep,
    model=model
)

# extract the raw displacements
displacement_fc = dpf.operators.result.raw_displacement(
    time_scoping=time_scoping,
    data_sources=model,
).eval()
print(displacement_fc)

# extract the field from the fields_container
disp_field = displacement_fc[0]
print(disp_field)

# one can access the field's underlying numpy.ndarray using ".data"
print(disp_field.data)

# save to csv
np.savetxt(
    'displacement2_pydpf-core.csv',
    X=disp_field.data,
    delimiter=',',  comments='', fmt='%.18e',
    header="UX, UY, UZ, RX, RY, RZ"
)

# optional: extract the rotational dofs from the field
rotational_disp = dpf.operators.logic.component_selector(
    field=disp_field,
    component_number=[3, 4, 5]
).eval()
print(rotational_disp)

```

**Comment by Tony-ooo** [comment]
> @PProfizi , please could you help @Tony-ooo , to get this use case working with pyDPF core and ensure that this is addressed with the new dpf-post API?

I have tested the new DPF-POST API "post.load_simulation" in ANSYS 2023R1, and it is functioning correctly. However, I have noticed that unlike pymapdl-reader, the new API is unable to extract the X, Y, and Z components of rotation from the rst file. It can only extract the X, Y, and Z components of displacement, which does not meet my requirements. Could you add the functionality of extracting the X, Y, and Z components of rotation in the new API? I am in urgent need of this feature.

**Comment by PProfizi** [comment]
Hi @Tony-ooo,
The reason you do not get identical field data for translational displacements between PyDPF-Core and PyDPF-Post is that when requesting them in PyDPF-Core, there is no specification of node IDs to request data for, and PyDPF-Core returns data as it is ordered server-side, which is not by ascending node ID.
When requesting the displacement data with PyDPF-Post however, you do indicate `node_ids=nnum`, which tells PyDPF-Post to request data _for those specific nodes IDs in that specific order_.

To obtain the same results, and as I guess you may want them ordered by ID for your .csv file to make sense, what you can do is modify the PyDPF-Core request as below:

```py
nnum = dat.nnum
node_scoping = dpf.mesh_scoping_factory.nodal_scoping(node_ids=nnum)

# extract the raw displacements
displacement_fc = dpf.operators.result.raw_displacement(
    time_scoping=time_scoping,
    mesh_scoping=node_scoping,
    data_sources=model,
).eval()
disp_field = displacement_fc[0]
```
This will result in `disp_field` having data ordered by node ID, and your .csv being identical for translational displacement.

**Comment by Tony-ooo** [comment]
Thank you very much for your assistance. You solved my problem perfectly. I'm looking forward to the addition of this feature in the PyDPF-Post API.

**Comment by akaszynski** [comment]
Thanks @PProfizi for your rapid follow up here.
