### ISSUE TITLE
Determining the principal directions

### ISSUE THREAD

**Issue by maximepollet27** [pyansys/pymapdl-reader#24]
Hi,

I am working on a stress analysis using SOLID185 elements and I am trying to determine the local coordinate system in which the principal stresses are. From looking at some other issues posted here before (https://github.com/pyansys/pymapdl/issues/283 and https://github.com/pyansys/pymapdl/issues/28), it seems that I will have to use the element Euler angles, which are stored in the binary file. I don't know how to access them though and I wonder if there is a method for it in `mapdl.result`, since Euler angles are displayed in the list of available results as shown below.

![image](https://user-images.githubusercontent.com/75030380/116418534-8783d480-a83c-11eb-996d-308fdfb06bdd.png)

My understanding is that the euler angles will allow me to determine the coordinate system in which the principal stresses are. However, once I know this local coordinate system, how do I determine on which axis is each principal stress?

Additionally, I wonder if the approach can be applied to both nodal and element stresses ?

Thank you for the help !

**Comment by maximepollet27** [comment]
Hi @akaszynski, 

Thank you for your reply, it really helps. The reason why I was trying to use the Euler angles was that I thought that these were the angles between the directions of the principal stresses and the global coordinate system. However, if I understand correctly, they are actually the angles between the global coordinate system and the local element coordinate system.

Still, I think I could "reverse" the code you posted to extract the right angles. The tensor would be as follows so that s_xx, s_yy, and s_zz are the principal stresses:
```
tensor = np.matrix([[s_xx, 0, 0],
                    [0, s_yy, 0],
                    [0, 0, s_zz]])
```
Then, using the equation `ans = R.T*tensor*R` and the values of `XX` ,`XY`, `YY`, `YZ`, `XZ`, `ZZ`, I could determine the three angles between the local principal stresses coordinate system and the global coordinate system. 
Would this approach make sense in your opinion?
Or maybe there is a method doing the same thing already built-in ?
Thanks again for the help.

**Comment by akaszynski** [comment]
> However, if I understand correctly, they are actually the angles between the global coordinate system and the local element coordinate system.

Correct.  One more detail: these are actually encoded at the "ElementNodal" level, which means that each node of each element has a (potentially) unique value.  The rotation of these results from the nodal coordinate system to the global coordinate system is handled in Cython at:
https://github.com/pyansys/pymapdl-reader/blob/4d5edad7f3784819b9edec994f2acf8d21c4964c/ansys/mapdl/reader/cython/_binary_reader.pyx#L733-L785

---
> Still, I think I could "reverse" the code you posted to extract the right angles

Solving for the principal directions requires you to solve for the eigenvectors of the stress tensor.  There's a great overview of that process [here](https://www.continuummechanics.org/principalstressesandstrains.html#:~:text=In%202%2DD%2C%20the%20principal,P%20%2C%20the%20principal%20stress%20angle.&text=Inserting%20this%20value%20for%20%CE%B8,stresses%20gives%20the%20principal%20values).

**Comment by maximepollet27** [comment]
Hi @akaszynski,

Thank you for your help, it all works fine now.
