### ISSUE TITLE
Numbering issue and type conversion of a pointer

### ISSUE THREAD

**Issue by Tyrin451** [pyansys/PyMAPDL-reader#31]
Hello,

In our usage of ANSYS APDL, we number the element type/real/section with a custom non contiguous numerotation.
In consequence I have relatively large number on element type/real/section (over 50 000).

In order to read my result file I had to modify the following files :

mesh.py line 121 :
`type_ref = np.empty(2 << 16, np.int32)  # 65536 -> 131072`

rst.py  (line 1342 to 1346):
```
NUM_MAX = 1000000 # <- new maximum
nodelm = np.empty(NUM_MAX, np.int32)  # n nodes for this element type
nodfor = np.empty(NUM_MAX, np.int32)  # n nodes per element having nodal forces
nodstr = np.empty(NUM_MAX, np.int32)  # n nodes per element having nodal stresses
ekey = []
keyopts = np.zeros((NUM_MAX, 11), np.int16)
```

During the exploration of my rst file (transient analysis of ~21Go), I encounter an OverflowError on cython (conversion of python int into C long...).
I circumvent this error by changing some type in _binary_reader.pyx (line 257 to 259)
```
def read_element_data(self, int64_t [::1] ele_ind_table, int table_index, int64_t ptr_off): #int -> int64_t
        cdef int64_t ind
        cdef int64_t ptr #int -> int64_t
```

I'm new to this library so may be my tweaks break something elsewhere. 
But it is possible to "officially" add some variable to configure the maximum int on element type/real/section and correct the type of the cython pointer ?

Thank you for the work on this lib ! 👍

**Comment by akaszynski** [comment]
> it is possible to "officially" add some variable to configure the maximum int on element type/real/section and correct the type of the cython pointer ?

These are great catches!  I'm implementing these fixes in a patch release of the reader.  Thanks for your work finding these issues.

**Comment by akaszynski** [comment]
@Tyrin451, please checkout https://github.com/pyansys/PyMAPDL-reader/tree/fix/typeref_int and let me know if it works for you.

If you're unfamiliar with git, you commands will be:
```py
git clone https://github.com/pyansys/PyMAPDL-reader/
git checkout fix/typeref_int
pip install -e .
```

You can forgo the `-e` flag, but I like to install with that mode when testing out things so I can quickly revert to master and reinstall.

**Comment by Tyrin451** [comment]
Thanks ! this patch work fine.

However I think that an optimization is required in binary_reader.pyx.

I loop over my results sets (~4000 ) and the time per call is not consistent. 
tqdm says 60it/s in the beginning then it fall to 8it/s.

On the 100 first sets I have the cProfile: 
```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
      100    0.983    0.010    0.983    0.010 {method 'read_element_data' of 'ansys.mapdl.reader._binary_reader.AnsysFile' objects}
  174/157    0.458    0.003    0.466    0.003 {built-in method _imp.create_dynamic}
      100    0.441    0.004    0.565    0.006 runPostPython.py:32(<listcomp>)
     2740    0.352    0.000    0.352    0.000 {built-in method nt.stat}
      100    0.124    0.001    0.140    0.001 rst.py:2321(<listcomp>)
      516    0.067    0.000    0.067    0.000 {built-in method io.open_code}
```

and for the all dataset
```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
     4231  206.065    0.049  206.065    0.049 {method 'read_element_data' of 'ansys.mapdl.reader._binary_reader.AnsysFile' objects}
     4231   36.187    0.009   44.205    0.010 runPostPython.py:32(<listcomp>)
     4231    7.058    0.002    7.932    0.002 rst.py:2309(<listcomp>)
   579647    4.292    0.000    6.807    0.000 runPostPython.py:18(mises1D)
        1    2.857    2.857  270.347  270.347 runPostPython.py:27(getMaxOverTime)
   588134    1.795    0.000    1.795    0.000 {method 'reduce' of 'numpy.ufunc' objects}
     8728    1.782    0.000    1.782    0.000 {method 'read_record' of 'ansys.mapdl.reader._binary_reader.AnsysFile' objects}
```

The append of the record to the pythonic list could be the problem  (_binary_reader.pyx line 283) ?

**Comment by Tyrin451** [comment]
Never mind, sometimes the iteration rates drop and sometimes not... I don't clearly identify why.

I think this issue can be closed. Thank you !

**Comment by akaszynski** [comment]
Read element data is remarkably inefficient and I've not put much effort in optimizing that since I've been under the assumption that most will use the nodal results (since it's one contiguous array of data).

200 seconds is pretty terrible.  Let me look into this and see if there's a way to optimize it.

**Comment by akaszynski** [comment]
Interestingly, I'm not seeing a huge variation between the array approach and the list approach.  For example, the same data ('ENS') with the list and then the array methods on a 6.6 GB file:

```py
>>> enum, edata, enode = rst.element_solution_data(0, 'ENS')
>>> enum, edata, enode = rst.element_stress(0)
```

Respective timing in seconds:
```
26.808578729629517
25.371294498443604
```

I'm also seeing some variation in the run times.  I think it has to do with the random read operations when working with the result file.  The way these results are organized is not conducive for efficient buffered reading.

Closing this with the merge of #32
