### ISSUE TITLE
Issues about reading results from rst file

### ISSUE THREAD

**Issue by 1990chs** [pyansys/PyMAPDL-reader#33]
I want to use this modulus in ANSYS act. The nodes are from ironPython and it is list(for example nodes = [1,2,3....1000]). The nodes have midside nodes. I want to get the cornor nodes stress values and temperatures. In the ANSYS classic, first use "nsle,r,corn" to remove the midside nodes and use *get to get the node value.
From issue pyansys/PyMAPDL#50 ,we can use the following codes to read result from *.rst file
```
from ansys.mapdl import reader as pymapdl_reader
resultfile = os.path.join(mapdl.path, '%s.rst' % mapdl.jobname)
result = pymapdl_reader.read_binary(result file)
```
So is there any way to remove midside cornor of the nodes list and get the cornor nodes values in result function?

**Comment by akaszynski** [comment]
I've transferred this from the other repository since this is the more relevant repository for reader related questions.

**Comment by 1990chs** [comment]
> I've transferred this from the other repository since this is the more relevant repository for reader related questions.

Thinks.By the way, is there ansy quick way to get the corresponding nodes values ？The way I think is using  the loop function  for each node in the nodes list (for example,nodes=[1,2,3,....,100]. But maybe Iit is very slow when the node number very biger.
Beside if the whole ANSYS rst mode very big, there maybe be not enough memory to use 'nnum, stress = result.nodal_stress(0) ' to get all the nodes values, for example the mode I creat have about two million nodes. So the result.nodal_stress() function can get only some nodes values , not all nodes values?Or is there any way to get it?

**Comment by akaszynski** [comment]
> By the way, is there ansy quick way to get the corresponding nodes values?

You'll want to use arrays.  Assuming you want nodes in the range of 1 - 1000:

```py
desired_nodes = np.arange(1, 1001)
mask = np.in1d(nnum, desired_nodes)
my_nodes = nnum[mask]
my_stress = stress[mask]
```

>  So the result.nodal_stress() function can get only some nodes values , not all nodes values?Or is there any way to get it?

At the moment it's configured to get all results, but that's actually something I can patch.  Look for the next release for this feature.

**Comment by 1990chs** [comment]
Thinks
`desired_nodes = np.arange(1, 1001)
mask = np.in1d(nnum, desired_nodes)
my_nodes = nnum[mask]
my_stress = stress[mask]
`
If the nodes number are not continuous, and I can translate the nodes list to numpy array, so the code `mask = np.in1d(nnum, desired_nodes)`  can also be used ?

**Comment by akaszynski** [comment]
> If the nodes number are not continuous, and I can translate the nodes list to numpy array,

Yes.  `numpy` is pretty smart and you can even have duplicate nodes and the mask will still work out.  You can test this with:

```py
>>> import numpy as np
>>> a = [1, 3, 4]
>>> b = [1, 2, 3, 4, 5]
>>> np.in1d(b, a)
array([ True, False,  True,  True, False])
```

**Comment by 1990chs** [comment]
> > If the nodes number are not continuous, and I can translate the nodes list to numpy array,
> 
> Yes. `numpy` is pretty smart and you can even have duplicate nodes and the mask will still work out. You can test this with:
> 
> ```python
> >>> import numpy as np
> >>> a = [1, 3, 4]
> >>> b = [1, 2, 3, 4, 5]
> >>> np.in1d(b, a)
> array([ True, False,  True,  True, False])
> ```

Thinks, so this issue will open and you can close it after patch this feature in the future.
If possible, it is better to path all the  relevant API.

**Comment by akaszynski** [comment]
Feature added in `ansys-mapdl-reader==0.51.0`.

**Comment by 1990chs** [comment]
> Feature added in `ansys-mapdl-reader==0.51.0`. Release should be out in an hour.

Thinks, I will update the ansys-mapdl-reader in next weekend. By the way does the document update ? So how to use it ?

**Comment by akaszynski** [comment]
Documentation does update automatically.  Docs can be found here:
https://readerdocs.pyansys.com/api/rst.html

I'll be adding a version to the most active docs so it's apparent what version is active.

**Comment by 1990chs** [comment]
> Documentation does update automatically. Docs can be found here:
> https://readerdocs.pyansys.com/api/rst.html
> 
> I'll be adding a version to the most active docs so it's apparent what version is active.

OK, Thinks

**Comment by 1990chs** [comment]
@akaszynski 
Hello, I have a problem to read the result when I read the nodes from a txt file.
But when I set the all_nodes a few nodes,it can work.
By the way, the result.principal_nodal_stress(0) read all the nodes result and I can't assign the the specific nodes.
![image](https://user-images.githubusercontent.com/27892759/122923602-72887500-d397-11eb-8972-e4ce6b2f1536.png)
