### ISSUE TITLE
Element numbering not being assigned to grid

### ISSUE THREAD

**Issue by akaszynski** [pyansys/pymapdl-reader#47]
Opened a new issue regarding this

@akaszynski 
Hello, I have a problem to read the result when I read the nodes from a txt file.
But when I set the all_nodes a few nodes,it can work.
By the way, the result.principal_nodal_stress(0) read all the nodes result and I can't assign the the specific nodes.
![image](https://user-images.githubusercontent.com/27892759/122923602-72887500-d397-11eb-8972-e4ce6b2f1536.png)

_Originally posted by @1990chs in https://github.com/pyansys/pymapdl-reader/issues/33#issuecomment-865938698_

Would it be possible to post the result file?

**Comment by 1990chs** [comment]
sorry, the result file in my company computer. It impossible to export result file. The nodes which stored in txt file have midnodes , does it influence the function?

**Comment by akaszynski** [comment]
It shouldn't,  I'll take a look at this error locally.  Effectively, the element number aren't being exported to the internal grid, and I can't tell why not.  Midside nodes shouldn't be contributing to this bug.

**Comment by 1990chs** [comment]
Ok. I will check it again. Maybe the nodes are not corrected. I need check.
```principal_nodal_stress(rnum)``` this API can't assign the nodes numbers . It needs update.

**Comment by akaszynski** [comment]
Thanks for letting me know.  I'll get working on this.

**Comment by 1990chs** [comment]
It seems that there are some problems to read nodes ID from txt file. I input the nodesID in python file directly, it can work, but there is a warining .
![image](https://user-images.githubusercontent.com/27892759/123086084-9611f500-d455-11eb-88bb-b8ab04093084.png)

**Comment by 1990chs** [comment]
the error solved , and I will open an issue #52 about the suggestion features

**Comment by 1990chs** [comment]
Why can't this issue  close?

**Comment by jgd10** [comment]
@1990chs I'll close the issue for you since it appears to be resolved!
