### ISSUE TITLE
Definition of ELEMENT_INDEX_TABLE_KEYS and ELEMENT_RESULT_NCOMP

### ISSUE THREAD

**Issue by NDfp** [pyansys/pymapdl-reader#49]
Hello,
Would it be possible to add the definition of the variables ELEMENT_INDEX_TABLE_KEYS and ELEMENT_RESULT_NCOMP to the Result class?
```
class Result(AnsysBinary):
    ELEMENT_INDEX_TABLE_KEYS = ELEMENT_INDEX_TABLE_KEYS
    ELEMENT_RESULT_NCOMP = ELEMENT_RESULT_NCOMP
```
In this way, they can be accessed from outside the rst.py file.
Thank you
Francesco

**Comment by akaszynski** [comment]
Will do.  How soon do you need this released?

**Comment by NDfp** [comment]
That is great, thanks.
As usual, the sooner the better ;o)
It would be good for the end of July.

**Comment by akaszynski** [comment]
I can have it by today, it's a trivial fix.  If you want, you can even fork and make a PR if you'd like to contribute (could even use the web interface).

Got a few other fires to put out first.

**Comment by NDfp** [comment]
No hurry.
I can try next week, so I learn how to do it.

**Comment by NDfp** [comment]
Closed in this [PR](https://github.com/pyansys/pymapdl-reader/pull/50).
Thank you!!

**Comment by akaszynski** [comment]
Well done with your first PR!
