### ISSUE TITLE
Weird black lines when using plot_nodal_solution or animate_nodal_solution

### ISSUE THREAD

**Issue by CesarRodriguezPereira** [pyansys/pymapdl-reader#57]
Hi,

I've just updated my pyansys installation from 0.58.9 to 0.59.3 and with the update, it seems like both of these reader functions are not functioning as well as they did before. When plotting results, now some black lines appear, worsening the view of solids and surfaces, and even completely obscuring the view of the result along line bodies.
A couple of images of this behaviour for reference:
Surface body - 
![image](https://user-images.githubusercontent.com/70496969/124449591-e6f1e980-dd83-11eb-9cee-833d479983d6.png)
Line body -
![image](https://user-images.githubusercontent.com/70496969/124449694-fcffaa00-dd83-11eb-89ef-c72490b13099.png)

**Comment by akaszynski** [comment]
Appears to be due to the normals calculated when enabling smooth shading.  Try `smooth_shading=False`.

**Comment by CesarRodriguezPereira** [comment]
> Appears to be due to the normals calculated when enabling smooth shading. Try `smooth_shading=False`.

Thanks, it works perfectly! Maybe that could be thrown in as a default value (if this is widespread at all), but is a really quick an easy fix!

**Comment by akaszynski** [comment]
I think changing that to default is a good idea since there's some funky behavior that happens in other plots as well.
