### ISSUE TITLE
nodes num can't mach

### ISSUE THREAD

**Issue by 1990chs** [pyansys/pymapdl-reader#58]
There is a strange question as follow. when I use nodal_stress(0,all_nodes) to  get nodal stress . But the len num don't match the len stress,it very strange. As follow, the length of num is 915980, it does't match the input nodes length. The length of stress is 893061, it is the same as the input nodes length. Why this happen ?
![image](https://user-images.githubusercontent.com/27892759/125622982-f2fd2af4-81e9-44b1-a762-a813a702ccda.png)

**Comment by 1990chs** [comment]
First I remove midnodes and the num lengh is the same as the stress length. But the stress result don't right related to interested nodes . If I input only one node, the stress is right . 
The FE model I used have several element types:  tetrahedron element ,pyramid element, hexahedra element, hexagonal element. The interface of elements have the same nodes.
So I guess there is some problems when get the stress from mixed elements.

**Comment by jgd10** [comment]
@1990chs It's been a while since you posted this; is it still an issue?

**Comment by 1990chs** [comment]
I change a different rst file, it  is right. The old rst result has pyramid element. You can check it. I will try to avoid using the pyramid element.Thinks.
I can close this issue.
