### ISSUE TITLE
comp_type in write_cmblock

### ISSUE THREAD

**Issue by AndreasGschwentner** [pyansys/pymapdl-reader#63]
Hey,

function write_cmblock() in archive.py isn't up to date. In the if-statement (line 626):

`if comp_type.upper() not in ['ELEMENT', 'NODE']`

ELEMENT has to be changed to ELEM.

Best regards 
Andreas

**Comment by akaszynski** [comment]
According to the Ansys Programmer's guide (as of 2021R2):

```
3.2.5. CMBLOCK Command
CMBLOCK defines the entities contained in a node or element component. The command format in

CMBLOCK,Cname,Entity,NUMITEMS,,,,,KOPT

Cname
    Eight character component name.
Entity
    Label identifying the type of component (NODE or ELEMENT).
```

Reference section 3.2.5 in:
[Ansys_Mechanical_APDL_Programmers_Reference.pdf](https://github.com/pyansys/pymapdl-reader/files/6935747/Ansys_Mechanical_APDL_Programmers_Reference.pdf)

---

Is there something else I'm missing?

**Comment by AndreasGschwentner** [comment]
Thanks for your answer.

That's interesting because in the cdb-Files I am working on, for the type of component ELEM is used and not ELEMENT.
I guess, both types are possible.
