### ISSUE TITLE
write_cmblock doesn't work by up_to = 0

### ISSUE THREAD

**Issue by AndreasGschwentner** [pyansys/pymapdl-reader#67]
Hey,

the command `write_cmblock` isn't working, when the variable `up_to = 0`.
In the cdb-file, the elements are written in one line. 

I think the problem is that `cmblock_items[:-0]` returns an empty array.

**Comment by akaszynski** [comment]
Thanks for pointing that out.  I'll have this patched in the next release.

**Comment by akaszynski** [comment]
I'm keeping this open so I'll remember to address this.
